# Generated by Django 3.2.6 on 2021-08-15 07:26

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('nombre', models.CharField(max_length=225, verbose_name='nombre')),
                ('sector', models.CharField(max_length=225, verbose_name='sector')),
                ('localidad', models.CharField(max_length=225, verbose_name='localidad')),
                ('nombre_encargado', models.CharField(max_length=225, verbose_name='nombre encargado')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=225, verbose_name='direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('ruc', models.IntegerField()),
                ('razon_social', models.CharField(max_length=225, verbose_name='razon_social')),
                ('total_comprado', models.IntegerField()),
                ('total_pagado', models.IntegerField()),
                ('deuda_por_pagar', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('monto', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('nombre', models.CharField(max_length=225, verbose_name='nombre')),
                ('sector', models.CharField(max_length=225, verbose_name='sector')),
                ('localidad', models.CharField(max_length=225, verbose_name='localidad')),
                ('nombre_encargado', models.CharField(max_length=225, verbose_name='nombre encargado')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=225, verbose_name='direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('ruc', models.IntegerField()),
                ('razon_social', models.CharField(max_length=225, verbose_name='razon_social')),
                ('total_comprado', models.IntegerField()),
                ('total_pagado', models.IntegerField()),
                ('deuda_por_pagar', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCobro',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('monto', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Cobro',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
