# Generated by Django 3.2.6 on 2021-09-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210908_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='encargado',
        ),
    ]
