# Generated by Django 3.2.6 on 2021-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20210908_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcobro',
            name='fecha',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
