# Generated by Django 3.2.6 on 2021-08-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_historicalproducto_history_user'),
        ('compras', '0003_auto_20210819_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='historicaldetallecompra',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.producto'),
        ),
    ]
