# Generated by Django 3.2.6 on 2021-08-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('costo', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('porc_iva', models.DecimalField(decimal_places=2, max_digits=2)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('ultima_compra', models.DateTimeField()),
            ],
        ),
    ]
