# Generated by Django 3.2.6 on 2021-08-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_historicalproducto_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto',
            name='porc_iva',
        ),
        migrations.RemoveField(
            model_name='historicalproducto',
            name='ultima_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='porc_iva',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ultima_compra',
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='autor',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='descripcion',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='autor',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='nombre',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=225),
        ),
    ]
